
import javax.swing.JOptionPane;
import user.User;
import user.UserDAO;
import captcha.TextToGraphics;
import captcha.CAPTCHA;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LeeJanyun
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    String currentCaptcha;  
    String userID = null;
    boolean isLogin = false;
    
    public MainFrame() {
        initComponents();
        lblImg.setText("");
        reset();
    }
    
    public void reset() {
        try {
            currentCaptcha = TextToGraphics.generateImage();
            Image img = ImageIO.read(new File("./src/captcha/Text.png"));
            lblImg.setIcon(new ImageIcon(img));
        } catch(IOException ex) {
            ex.printStackTrace();
        }
    }
    
    public int checkCaptcha() {
        if(inputCaptcha.getText().equals(currentCaptcha) ) {
            return 1;
        } else {
            return -1;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupGender = new javax.swing.ButtonGroup();
        groupActivity = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        inputAge = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        radioAct1 = new javax.swing.JRadioButton();
        radioAct2 = new javax.swing.JRadioButton();
        radioAct3 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        radioAct4 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        radioAct5 = new javax.swing.JRadioButton();
        inputID = new javax.swing.JTextField();
        btnSignUp = new javax.swing.JButton();
        radioM = new javax.swing.JRadioButton();
        radioF = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        inputHeight = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        inputWeight = new javax.swing.JTextField();
        inputPW = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        InputLoginID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblImg = new javax.swing.JLabel();
        inputCaptcha = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        resetChaptcha = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        InputLoginPW = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        jLabel7.setFont(new java.awt.Font("궁서", 0, 13)); // NOI18N
        jLabel7.setText("나이 : ");

        jLabel8.setFont(new java.awt.Font("궁서", 0, 13)); // NOI18N
        jLabel8.setText("활동량");

        groupActivity.add(radioAct1);
        radioAct1.setFont(new java.awt.Font("궁서", 0, 13)); // NOI18N
        radioAct1.setText("적음(운동안함)");

        groupActivity.add(radioAct2);
        radioAct2.setFont(new java.awt.Font("궁서", 0, 13)); // NOI18N
        radioAct2.setText("보통(1~3일운동)");

        groupActivity.add(radioAct3);
        radioAct3.setFont(new java.awt.Font("궁서", 0, 13)); // NOI18N
        radioAct3.setText("조금(3~5일운동)");

        jLabel1.setFont(new java.awt.Font("궁서", 0, 13)); // NOI18N
        jLabel1.setText("아이디(ID)     :");

        groupActivity.add(radioAct4);
        radioAct4.setFont(new java.awt.Font("궁서", 0, 13)); // NOI18N
        radioAct4.setText("많음(5~7일운동)");

        jLabel2.setFont(new java.awt.Font("궁서", 0, 13)); // NOI18N
        jLabel2.setText("비밀번호(PW)  :");

        groupActivity.add(radioAct5);
        radioAct5.setFont(new java.awt.Font("궁서", 0, 13)); // NOI18N
        radioAct5.setText("매우많음(하루 두번)");

        btnSignUp.setFont(new java.awt.Font("궁서", 1, 14)); // NOI18N
        btnSignUp.setText("회원가입");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        groupGender.add(radioM);
        radioM.setFont(new java.awt.Font("궁서", 0, 13)); // NOI18N
        radioM.setText("남성");
        radioM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMActionPerformed(evt);
            }
        });

        groupGender.add(radioF);
        radioF.setFont(new java.awt.Font("궁서", 0, 13)); // NOI18N
        radioF.setText("여성");

        jLabel5.setFont(new java.awt.Font("궁서", 0, 13)); // NOI18N
        jLabel5.setText("키 : ");

        jLabel6.setFont(new java.awt.Font("궁서", 0, 13)); // NOI18N
        jLabel6.setText("몸무게 : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputID, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(inputPW)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(radioM)
                                .addGap(61, 61, 61)
                                .addComponent(radioF))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inputHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inputAge, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(radioAct4)
                                .addGap(40, 40, 40)
                                .addComponent(radioAct5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(radioAct1)
                                .addGap(27, 27, 27)
                                .addComponent(radioAct2)
                                .addGap(18, 18, 18)
                                .addComponent(radioAct3))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(btnSignUp)))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inputID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inputPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioF)
                    .addComponent(radioM))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(inputHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(inputAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(inputWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioAct1)
                    .addComponent(radioAct2)
                    .addComponent(radioAct3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioAct4)
                    .addComponent(radioAct5))
                .addGap(51, 51, 51)
                .addComponent(btnSignUp)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("회원가입", jPanel1);

        jLabel9.setFont(new java.awt.Font("궁서", 0, 13)); // NOI18N
        jLabel9.setText("아이디(ID)     :");

        jLabel10.setFont(new java.awt.Font("궁서", 0, 13)); // NOI18N
        jLabel10.setText("비밀번호(PW)  :");

        lblImg.setText("jLabel3");

        jLabel11.setFont(new java.awt.Font("궁서", 0, 13)); // NOI18N
        jLabel11.setText("본인문자 입력    :");

        resetChaptcha.setFont(new java.awt.Font("궁서", 0, 13)); // NOI18N
        resetChaptcha.setText("새로고침");
        resetChaptcha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetChaptchaActionPerformed(evt);
            }
        });

        btnLogin.setFont(new java.awt.Font("궁서", 0, 13)); // NOI18N
        btnLogin.setText("확인");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("궁서", 0, 13)); // NOI18N
        jLabel12.setText("보안문자");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resetChaptcha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(jLabel9))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(jLabel10)))
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(InputLoginID)
                                            .addComponent(InputLoginPW, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(inputCaptcha, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btnLogin)
                        .addGap(83, 83, 83))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputLoginID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(InputLoginPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(resetChaptcha))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(inputCaptcha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogin))
                .addGap(102, 102, 102))
        );

        jTabbedPane1.addTab("로그인", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("식단 입력", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("최근 식단", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        UserDAO userDAO = new UserDAO();
        User user = new User();
        user.setUserID(inputID.getText());
        user.setUserPassword(inputPW.getText());
        double activity;
        int Calorie;
        
        if(radioAct1.isSelected()){
            activity = 1.2;
        }else if(radioAct2.isSelected()){
            activity = 1.375;
        }else if(radioAct3.isSelected()){
            activity = 1.55;
        }else if(radioAct4.isSelected()){
            activity = 1.725;
        }else if(radioAct5.isSelected()){
            activity = 1.9;
        }else {
            activity = 0;
        }
        if(radioM.isSelected()){
            user.setUserGender("남성");
            HWACheck();
            Calorie = (int) ((66.0 +(13.7 * Double.parseDouble(inputWeight.getText())) 
                    + (5 * Double.parseDouble(inputHeight.getText())) 
                    - (6.8 *  Double.parseDouble(inputAge.getText())))*activity);
        }
        else if(radioF.isSelected()){
            user.setUserGender("여성");
            HWACheck();
            Calorie =  (int)((665.0 +(9.6 * Double.parseDouble(inputWeight.getText())) 
                    + (1.7 *Double.parseDouble(inputHeight.getText())) 
                    - (4.7 * Double.parseDouble(inputAge.getText())))*activity);
        }
        else{
            Calorie = 0;
        }
        
        user.setUserCalorie(Calorie);
        
        if(user.getUserID() == null || user.getUserID().equals("")) {
            JOptionPane.showMessageDialog(null, "아이디를 입력해주세요");
            return;
        }
        if(userDAO.checkID(user.getUserID()) == 1) {
            JOptionPane.showMessageDialog(null, "이미 존재하는 ID입니다.");
            return;
        }
        if(user.getUserPassword() == null || user.getUserPassword().equals("")) {
            JOptionPane.showMessageDialog(null, "비밀번호를 입력해주세요");
            return;
        }
        if(user.getUserGender() == null || user.getUserGender().equals("")){
            JOptionPane.showMessageDialog(null,"성별을 골라주세요");
            return;
        }
        HWACheck();
        
        if(user.getUserCalorie() == 0){
            JOptionPane.showMessageDialog(null,"활동량을 선택해주세요");
            return;
        }
        
        if(userDAO.join(user) == 1) {
            JOptionPane.showMessageDialog(null, "성공적으로 아이디를 등록했습니다.");
            return;
        }
        JOptionPane.showMessageDialog(null, "무언가 오류가 발생했습니다.");
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void radioMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioMActionPerformed

    private void resetChaptchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetChaptchaActionPerformed
        reset();
    }//GEN-LAST:event_resetChaptchaActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        UserDAO userDAO = new UserDAO();
        int login = 0;
        if(InputLoginID.getText()==null || InputLoginID.getText().equals("")){
            JOptionPane.showMessageDialog(null, "아이디를 입력해 주세요.");
            return;
        }
        
        if(InputLoginPW.getText()==null || InputLoginPW.getText().equals("")){
            JOptionPane.showMessageDialog(null, "비밀번호를 입력해 주세요.");
            return;
        }
        
        if(checkCaptcha() != 1) {
            JOptionPane.showMessageDialog(null, "캡차를 확인해주세요");
            return;
        }
        
        login = userDAO.login(InputLoginID.getText(), InputLoginPW.getText());
         if (login == -1){
            JOptionPane.showMessageDialog(null, "없는 ID 입니다.");
            return;
        }
         else if (login == 0){
            JOptionPane.showMessageDialog(null, "비밀번호가 틀렸습니다.");
            return;
         }
        else if(login == 1){
            userID = InputLoginID.getText();
            JOptionPane.showMessageDialog(null, userID + "님, 안녕하세요!");
            isLogin = true;
        }else{
            JOptionPane.showMessageDialog(null,"데이터베이스 오류");
        }
    }//GEN-LAST:event_btnLoginActionPerformed
    
    public void HWACheck(){
        double test = 0;
        if(inputHeight.getText()==null|| inputHeight.getText().equals("")){
            JOptionPane.showMessageDialog(null,"키를 입력해 주세요");
            return;
        }else{
            try {
                test = Double.parseDouble(inputHeight.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,"키는 숫자만 입력해 주세요");
                return;
            }
        }
        if(inputWeight.getText()==null|| inputWeight.getText().equals("")){
            JOptionPane.showMessageDialog(null,"몸무게를 입력해 주세요");
            return;
        }else{
             try {
                test = Double.parseDouble(inputWeight.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,"몸무게는 숫자만 입력해 주세요");
                return;
            }
        }
        
        if(inputAge.getText()==null|| inputAge.getText().equals("")){
            JOptionPane.showMessageDialog(null,"나이를 입력해 주세요");
            return;
        }else{
             try {
                test = Double.parseDouble(inputAge.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,"나이는 숫자만 입력해 주세요");
                return;
            }
        }
        
    }
    
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InputLoginID;
    private javax.swing.JPasswordField InputLoginPW;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignUp;
    private javax.swing.ButtonGroup groupActivity;
    private javax.swing.ButtonGroup groupGender;
    private javax.swing.JTextField inputAge;
    private javax.swing.JTextField inputCaptcha;
    private javax.swing.JTextField inputHeight;
    private javax.swing.JTextField inputID;
    private javax.swing.JPasswordField inputPW;
    private javax.swing.JTextField inputWeight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblImg;
    private javax.swing.JRadioButton radioAct1;
    private javax.swing.JRadioButton radioAct2;
    private javax.swing.JRadioButton radioAct3;
    private javax.swing.JRadioButton radioAct4;
    private javax.swing.JRadioButton radioAct5;
    private javax.swing.JRadioButton radioF;
    private javax.swing.JRadioButton radioM;
    private javax.swing.JButton resetChaptcha;
    // End of variables declaration//GEN-END:variables
}
